version: '2'
services:
  consumer:
    image: sample-consumer:latest
  published:
    image: sample-publisher:latest
  web:
    image: sample-web:latest
    ports:
      - "8080:8080"
  nginx:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - ./web/src/main/resources/webroot:/usr/share/nginx/html
      - ./web/src/main/resources/nginx/nginx.conf:/etc/nginx/conf.d/default.conf